### ISSUE TITLE
possible use the react-router Link element?

### ISSUE THREAD

**Issue by rkoberg** [wrakky/react-html-parser#10]
Is there some way (feature request) to allow a parse of custom React elements? For example, I want to have a control on my wysiwyg editor for admins to be able to add internal links. This would need to use the react-router Link element (I assume). Or perhaps there is another way to handle it?

**Comment by dlim-dlim** [comment]
+1 Would also like to know best way convert use react-router Link...

Is there a way to convert <a> tags or a way to use Link if Link markup is already part of the string?

**Comment by wrakky** [comment]
This is now possible using the new `transform` function option. Something like this should probably work:

```js
function transform(node) {
  if (node.type === 'tag' && node.name === 'a') {
    return <Link to={node.attribs.href}>Link text</Link>
  }
}
```

**Comment by salientknight** [comment]
@wrakky Do you have a full example? Once I write the function, how to I pass it HTMLparser? Or do I write it inside in the parser call it self?
