### ISSUE TITLE
error cannot find module

### ISSUE THREAD

**Issue by dpyudha** [wrakky/react-html-parser#13]
i got this error
"Uncaught Error: Cannot find module "../maps/decode.json" "
Module parse failed: /home/dicki/dev/node_modules/entities/maps/decode.json Unexpected token 

what should i do ?

thankyou

**Comment by ihortkachuk** [comment]
I think you need to install `json-loader`.

**Comment by wrakky** [comment]
Doesn't look like an issue with react-html-parser
