### ISSUE TITLE
Really wish I could override the react element without parsing attrs and children

### ISSUE THREAD

**Issue by tannerlinsley** [wrakky/react-html-parser#27]
You do some great work here: https://github.com/wrakky/react-html-parser/blob/master/src/elementTypes/TagElementType.js#L17-L31

But honestly I would really like to simply use to those processed props and children in my own react element here: https://github.com/wrakky/react-html-parser/blob/master/src/elementTypes/TagElementType.js#L34

Thoughts?

**Comment by wrakky** [comment]
What do you mean by your own react element? You want to use the props and children outside of ReactHtmlParser?

**Comment by tannerlinsley** [comment]
I would be looking for something like this:
```javascript
const overrideComponents = {
  h1: styled.h1`font-size: 3rem;`,
  h2: styled.h2`font-size: 2.5rem;`,
  h3: styled.h3`font-size: 2rem;`,
  ...
}

(node, index) => {
  if (node.type === 'tag' && overrideComponents[node.name]) {
    const preprocessedNode = preprocessNode(node, index)
    return React.createElement(
      components[node.name],
      preprocessedNode.props,
      preprocessedNode.children
    )
  }
}
```

It doesn't seem like this is possible right now, since all of the props and children coming from `node` have not be "react-ified".  Right?

**Comment by tannerlinsley** [comment]
The above example is under the assumption that the `preprocessNode` function would available as an export and pretty do what `nodeToElement` does, but defer the element creation to the user.

**Comment by wrakky** [comment]
If you're using some kind of module loader then all of the required functions are already exposed. I think you should be able to achieve what you need by doing the following:

```js
import { processNodes } from 'react-html-parser';
import generatePropsFromAttributes from 'react-html-parser/lib/util/generatePropsFromAttributes';

const transform = (node, index) => {
  if (node.type === 'tag' && overrideComponents[node.name]) {
    return React.createElement(
      overrideComponents[node.name],
      generatePropsFromAttributes(node.attributes, index),
      processNodes(node.children, transform)
    )
  }
}
```

Your `preprocessNode` function would pretty much just return the results from those two function calls anyway.

**Comment by tannerlinsley** [comment]
That works great! Thanks for the shortcut :)
