### ISSUE TITLE
classname in figcaption

### ISSUE THREAD

**Issue by SnowDiamond** [wrakky/react-html-parser#29]
First of all, thank you for the library! I'm using it to render HTML string from draft.js. When the string contains figure with image and image caption I got an error:

```
warning.js:33 Warning: Unknown DOM property classname. Did you mean className?
    in figcaption (created by Story)
    in figure (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in article (created by Story)
    in div (created by Story)
    in div (created by Story)
    in div (created by Story)
    in Story (created by StoryContainer)
    in StoryContainer (created by Connect(StoryContainer))
    in Connect(StoryContainer) (created by RouterContext)
    in div (created by _default)
    in div (created by _default)
    in div (created by _default)
    in _default (created by RouterContext)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
    in AppContainer
```
Any thoughts why this happens?

**Comment by wrakky** [comment]
You get this warning with React 16 when you add the `classname` attribute to an element. Prior to v16, React had an attribute whitelist and it would strip out any attributes it didn't think were valid (such as `classname`). If you use the `class` attribute in your HTML strings `react-html-parser` will automatically convert it to `className`.

**Comment by SnowDiamond** [comment]
@wrakky thanx for answer :) but I think problem with `react-html-parser` because I use exactly `className`. And this errors appears only on component with `react-html-parser` and only if html string contain image. Please try to use my html string
```
"<p class=\"md-block-unstyled\">Most people believe <strong class=\"md-inline-bold\">Christmas</strong> is a winter holiday, that requires some snow, fir-trees and permanent jingling. Still, there is a belief that it could be just as awesome in tropical environment with palms, mojito and sunbathing.</p><blockquote class=\"md-block-blockquote\">Christmas is also a time of the year when we opt for sophisticated and unusual meals, even when celebrating at home. If you are a bit of a gourmet you may find it curious to visit the Hong Kong food festival. </blockquote><p class=\"md-block-unstyled\">So let’s have a look at options to celebrate Christmas and New Year in a warm weather. Consider wearing shorts and flip-flops instead of a sweater with deer.</p><h3 class=\"md-block-header-three\">Taking a Cruise</h3><p class=\"md-block-unstyled\">This way of celebrating is great for those who want to embrace all the joys having very little time. You can combine relaxing on the deck with occasional sightseeing and shopping in new cities.</p><figure class=\"md-block-image\"><img src=\"http://localhost:3000/uploads/photo/file/256/modal_get-started.jpeg\" alt=\"\" /><figcaption className=\"md-block-image-caption\"></figcaption></figure><p class=\"md-block-unstyled\">The decorated fir-trees are probably making funny jingling noises because of the waves. Ok, just kidding, modern cruise ships are not so sensitive. Still, make sure that you and your companions are not sea-sick. </p>"
```

**Comment by wrakky** [comment]
This is the offending section:
`<figcaption className=\"md-block-image-caption\"></figcaption>`

That attribute should be `class` and not `className`. `react-html-parser` automatically converts all attributes to lowercase because React throws other warnings for unknown attributes that are in camel case, so this converts `className` to `classname` and then you get the warning about using `classname` instead of `className` that you are seeing.

**Comment by SnowDiamond** [comment]
I got it! Thank you!

**Comment by andrewhheller** [comment]
Hi, thanks for the thread - 

Does anyone know how I can transform classnames as variables?

EXAMPLE:

ReactHtmlParser('<h1 className={ headingsCSS.pageL1 }>My Heading</h1>')

not working...
