### ISSUE TITLE
Ignore certain elements in <pre> or <code> tags

### ISSUE THREAD

**Issue by antonbehaeghe** [wrakky/react-html-parser#32]
Is there a way to ignore certain HTML elements inside pre or code tags?
Let's say I have the following HTML string: `<pre><div class="code-example></div></pre>`

This will render a pre tag and a div to the page, but I want the pre tag as an actual tag, and the div as text. However, should there be any `<br />` tags inside the `<pre>`, they should be rendered as a tag as well.

**Comment by wrakky** [comment]
You should be able to use a [transform](https://github.com/wrakky/react-html-parser#transform-function) function to achieve this.

Each time `tranform` is called it is passed the current node, which includes information about it's parent. Using this you can walk up the node hierarchy and figure out if any node is inside a `<pre>` tag and then transform it into the shape that you want.

```js
function transform(node) {
  if (node.parent.type === 'tag' && node.parent.name === 'pre') {
    // node is inside a <pre> tag so do something different to it
  }
}
```

There's an example of transform in action as part of the [demo site](https://wrakky.github.io/react-html-parser/).

**Comment by antonbehaeghe** [comment]
I'll give that a try! I did however find another way to solve my problem. By replacing the '<' and '>' tags with html entities (&lt; &gt;) the string just gets rendered as text and not as a react element.

**Comment by wrakky** [comment]
That's probably an easier way to do it if you can do that before passing anything to `react-html-parser`. Then the library will just treat the entire contents of the `<pre>` tag as one big string and you won't need to do any additional processing to check the parent for every node.
