### ISSUE TITLE
is it possible to convert nodes back to an html string?

### ISSUE THREAD

**Issue by chrisdobler** [wrakky/react-html-parser#38]
can the nodes be parsed back to a string of html?

**Comment by wrakky** [comment]
There's nothing built into the library for this. I guess you could use [ReactDOMServer.renderToString](https://reactjs.org/docs/react-dom-server.html#rendertostring) to convert the React element returned from the html parser back into a string?

**Comment by chrisdobler** [comment]
interesting, thats what I was wondering. For my use case i thought i needed this, but ended up that I only needed process nodes function. I was having trouble hooking up an event handler to a form, but got it hooked up now! thanks for the great work.
