### ISSUE TITLE
Passing in local image via require()

### ISSUE THREAD

**Issue by Dragonite** [wrakky/react-html-parser#60]
`<img src={require("local image path here")}/>`

Currently parsing this in does not use the image, as I believe the `require()` function isn't actually recognised as a function. My current workaround is just using an actual online link, however is this an issue that can be resolved in some way?

**Comment by DoMiNeLa10** [comment]
Are you using a fixed string or one with an arbitrary value? Your build system might be not able to pick up dynamically generated paths to imports.

**Comment by Dragonite** [comment]
@DoMiNeLa10 I was using a fixed string.

**Comment by DoMiNeLa10** [comment]
In that case you might have a problem with configuration of your build system. Try logging the return value of that `require()`.
