### ISSUE TITLE
Impossible to render a customComponent

### ISSUE THREAD

**Issue by javierxbrenes1** [wrakky/react-html-parser#64]
Hi Guys, I have this html as text:
`<p><span>Based on</span><MathSymbolWrapper value={"f: ]1/3, +infty[ rightarrow P"} /></p>`

MathSymbolWrapper  is a custom component to show a math function.

Using ReactHtmlParser the custom component it's not rendered, It comes in lower case.

So the question is, can I use ReactHtmlParser to parser custom react components? if I do, how can I accomplish this ?

**Comment by javierxbrenes1** [comment]
I already figured it out, using transform function.

**Comment by dingchaoyan1983** [comment]
can you tell me how to implement? because the 
```
export default function isValidTagOrAttributeName(tagName) {
  if (!nameCache.hasOwnProperty(tagName)) {
    nameCache[tagName] = VALID_TAG_REGEX.test(tagName);
  }
  return nameCache[tagName];
}
```

this will not validate passed.

**Comment by javierxbrenes1** [comment]
I did this in this way 
``` 
{
ReactHtmlParser(quesDes, 
{transform: function(node, index) {
				if(node.type ==="tag" && node.name === "mathsymbolwrapper"){
					return <MathSymbolWrapper key={index} value={node.attribs['value']}/>
                }
                if(node.type === "tag" && node.name === "mathsymbolwrappertext" ){
                    return <MathSymbolWrapperText key={index} value={node.attribs['value']} />
                }
            }
})
}
```
basically `ReactHtmlParser` receives two arguments here, the string that is your `raw Html`, and an object
with a property called `transform`, this is a function, so for every node `ReactHtmlParser` finds in the string, this function is executed, in this case I check by type and name and I return the real React component.

**Comment by dingchaoyan1983** [comment]
@javierxbrenes1 thanks very much

**Comment by coach-arne** [comment]
> I did this in this way
> `{ ReactHtmlParser(quesDes, {transform: function(node, index) { if(node.type ==="tag" && node.name === "mathsymbolwrapper"){ return <MathSymbolWrapper key={index} value={node.attribs['value']}/> } if(node.type === "tag" && node.name === "mathsymbolwrappertext" ){ return <MathSymbolWrapperText key={index} value={node.attribs['value']} /> } } }) }`
> basically ReactHtmlParser receives to arguments here, the string that is your raw Html, and an object
> with a property called transform, this is a function, so for every node ReactHtmlParser finds in the string, this function is executed, in this case I check by type and name and I return the real React component.

I was unable to use the children, do you have any idea how to include these?

for example `<Try><p>test</p></Try>`. 

Did not work when: 
`
if (node.type === 'tag' && node.name === "try") {
      return <Try>{node.children}</Try>
}
`

**Comment by kaijuh** [comment]
> I did this in this way `{ ReactHtmlParser(quesDes, {transform: function(node, index) { if(node.type ==="tag" && node.name === "mathsymbolwrapper"){ return <MathSymbolWrapper key={index} value={node.attribs['value']}/> } if(node.type === "tag" && node.name === "mathsymbolwrappertext" ){ return <MathSymbolWrapperText key={index} value={node.attribs['value']} /> } } }) }` basically ReactHtmlParser receives to arguments here, the string that is your raw Html, and an object with a property called transform, this is a function, so for every node ReactHtmlParser finds in the string, this function is executed, in this case I check by type and name and I return the real React component.

Thanks for adding this example. I was able to render my custom react component but the issue I am having is that none of the HTML found after the react component is rendering. Are you having the same issue if you try to use a custom react component in the middle of your html?

Thanks
