### ISSUE TITLE
Ignoring <script> tags?

### ISSUE THREAD

**Issue by hauptrolle** [wrakky/react-html-parser#67]
Hi 👋 ,

first of all, thank you for your work on this package. It works great expect for one case:
Parsing `<script>` tags.
I prepared a codesandbox for this. As you can see the script tag is not rendered at all.

Codesandbox: https://codesandbox.io/s/vigorous-boyd-ptj8y

Did I miss some kind of configuration to handle script tags properly?

Cheers,
Achim

**Comment by martin-eq** [comment]
@hauptrolle I think this is similar to this issue in a similar library to this:
https://github.com/remarkablemark/html-react-parser/issues/98

TL;DW: It seems `react-dom` ignores `script` elements.

**Comment by hauptrolle** [comment]
@martin-eq Yeah, I found this issue as well. Sad that `react-dom` is ignoring it 😞 I will close this issue...
