### ISSUE TITLE
malfunctioning due to presence of <=

### ISSUE THREAD

**Issue by shubhamjadon** [wrakky/react-html-parser#72]
In my project i have used react-html-parser on the user input, so that i can use <br>,etc while printing them. But there is some issue with <= as when i am writing <= in the text passed to react-html-parser it is only returning text before it. <= along with text after it are missing. Also problem solves when i write it like < = (with space b/w it). Any suggestions on how to get rid of it. 
I tried passing "this is awesome <= nothing" to react-html-parser and it returned just this returned Array of length 1 containing  only "this is awesome"

**Comment by rgvillanueva28** [comment]
Same problem. Have you managed to fix it?

My case:
I am writing a code "... if (num <= size): ...", it only displays "... if(num ".

**Comment by shubhamjadon** [comment]
@rgvillanueva28 i was not able to fix it.

**Comment by rgvillanueva28** [comment]
Well I've used another library but I think you can fix it by encoding the string.
You can use [@this site](https://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=utf_8)

**Comment by shubhamjadon** [comment]
Thanks @rgvillanueva28 I will try that.

**Comment by LiMao00** [comment]
`num < size || num === size`, I wrote it this way
