### ISSUE TITLE
react-html-parser onClick handler not included

### ISSUE THREAD

**Issue by suneethar** [wrakky/react-html-parser#8]
Hi,

react-html-parser works fine for tags but its not including onClick events if present in my string , how to make it to include onClcik event also.

Thanks and Regards,
suneetha R

**Comment by wrakky** [comment]
The parser doesn't support executing javascript through event handlers due to security concerns. You might be able to do something custom using the new `transform` function and eval but it is not recommended.

**Comment by skizzo** [comment]
This is doable with a little workaround, although not for nested links (I assume). The trick is to surround your _clickable_ links with your own click handler and set the links themselves _unclickable_ by disabling `pointerEvents` for them. Insert a middle man, so to say.

```
import React, {Component, PropTypes} from "react"
import ReactHtmlParser, {convertNodeToElement} from "react-html-parser"

class HTMLCanvas extends Component {

  static propTypes = {
    htmlContent: PropTypes.string.isRequired,
    // ..
  }

  // ...

  htmlParserTransform = (node, index) => {
    if (node.type == "tag" && node.name == "a") { // a tag named a
      const {href} = node.attribs // extract the actual url
      return (
        <a 
          href={href} // show it as the actual url, e.g. when hovered over, ..
          onClick={(event) => {
            event.preventDefault () // .. but prevent the default behaviour
            //	now, do whatever you want with href, for example:
            window.open (href, "_blank")
          }}
          >
          <span pointerEvents="none">
            {convertNodeToElement (node, index, this.htmlParserTransform)}
          </span>
        </a>
      )
    }

  }
  render = () => {
    return ReactHtmlParser (
      this.props.htmlContent, // or whatever
      {transform: this.htmlParserTransform}
     ) 
  }
}
export default HTMLCanvas
```
Works like a charm using `react-html-parser` version `2.0.0`.
